name: Deploy Core API

on:
  workflow_run:
    workflows:
      - "CI - Build & Push Docker Images"
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read

env:
  APP_NAME: loverace-core-api
  RG: ${{ secrets.AZURE_RESOURCE_GROUP }}
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/loverace-core-api

jobs:

  deploy:
    runs-on: ubuntu-latest

    if: |
      github.event.workflow_run.conclusion == 'success'

    steps:

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Configure App Service Container
        run: |
          az webapp config container set \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RG }} \
            --docker-custom-image-name ${{ env.IMAGE }}:latest \
            --docker-registry-server-url https://index.docker.io \
            --docker-registry-server-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-registry-server-password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Restart App Service
        run: |
          az webapp restart \
            --name ${{ env.APP_NAME }} \
            --resource-group ${{ env.RG }}